### ISSUE TITLE
Bugs in server when starting with a non-empty disk cache

### ISSUE THREAD

**Issue by vdjeric** [mozilla/Snappy-Symbolication-Server#22]
1) Lots of libraries weren't pickled properly for some reason
2) There were multiple paths in the code along which exceptions were getting thrown (and not caught). These exceptions didn't get logged either

**Comment by vdjeric** [comment]
These are mostly addressed in pull 60d43326873603c71c8f2cdec93f519736254da9

**Comment by willkg** [comment]
The caching has changed, so I'm pretty sure this isn't valid anymore. Closing it out--reopen if it's still relevant.
