### ISSUE TITLE
Make the disk and memory cache sizes use byte values instead of number of files/symbol maps

### ISSUE THREAD

**Issue by gabrielesvelto** [mozilla/Snappy-Symbolication-Server#24]
One of the issues we ran into recently is the disk getting filled up with symbol files before we hit the maximum number of files limit. Since there's no telling how large each file is going to be the cache sizes (memory and disk) should use byte values instead of number of files. That would allow precise control of how much space we're using at most.

**Comment by willkg** [comment]
@bytesized: Is this valid anymore?

**Comment by bytesized** [comment]
@willkg I believe this issue is fixed. The rewrite tracks the size of the file cache rather than the number of files. There is more information about the specifics in the README if you are interested.

**Comment by willkg** [comment]
Awesome--closing this one out.
