### ISSUE TITLE
Evaluate compressing symbol files

### ISSUE THREAD

**Issue by gabrielesvelto** [mozilla/Snappy-Symbolication-Server#25]
Symbol files tend to compress very well: 80%+ when using `gzip --fast`, possibly much more with more aggressive compression. We should evaluate storing the symbol files in compressed format to disk; it could dramatically increase the effective size of the cache.

**Comment by rhelmer** [comment]
Symbol files are (or at least should be!) compressed when they are uploaded to S3 - you should only have to set the proper `Accept-Encoding` header in the request.

**Comment by gabrielesvelto** [comment]
I'm not fluent in Python but if I'm reading this correctly it seems like we do indeed fetch compressed symbol files but then unpack them on disk when they're stored in the cache:

https://github.com/mozilla/Snappy-Symbolication-Server/blob/master/symFetcher.py#L73

**Comment by rhelmer** [comment]
Hm yeah I think what's doing there is reading the file into memory (into `StringIO` which is an in-memory "file-like" object).

Later when this is stored to disk this should either be re-compressed, or perhaps the in-memory representation should be gzipped if this only ends up being read once.

This is the only place I see cache files being written:
https://github.com/mozilla/Snappy-Symbolication-Server/blob/master/symCache.py#L113

**Comment by rhelmer** [comment]
If that is indeed the right place, the easy way to re-compress would be something like:

```
import gzip
(...)
with gzip.open(path, 'wb') as f:
  pickle.dump(symbolInfo, f, pickle.HIGHEST_PROTOCOL)
```

And of course also when reading the serialized ("pickled") file later:

```
with gzip.open(path, 'rb') as f:
  symbolInfo = pickle.load(f)
```

I would write this as a patch instead of a github comment, but someone should make sure this is indeed the right place :)

**Comment by willkg** [comment]
I'm game for meddling here. Are the docs on MDN linked to in the README the best way to get this project set up for testing things out?

**Comment by rhelmer** [comment]
Hmmm so @willkg pointed out in IRC that I didn't think through https://github.com/mozilla/Snappy-Symbolication-Server/issues/25#issuecomment-226812442 before writing it, sorry :/

So here's what's up:
1. sym file is downloaded (accept-encoding: gzip) from S3
2. file is gunzipped into memory (stringio) and then parsed into a `SymbolInfo`
3. the parsed in-memory datastructure (`SymbolInfo`) is serialized ("pickled")

Next time a request comes in for that symbol, the serialized `SymbolInfo` is used instead.
Also the `pickle.HIGHEST_PROTOCOL` is a binary format.

So, it's not clear that just blindly gzipping the pickle is going to help. @willkg is going to compare the size of a gzipped file vs. the pickle, it really depends on what is being retained in that data structure.

**Comment by gabrielesvelto** [comment]
When I tested this I compressed one of the files found on the server's cache using `gzip --fast` and it yielded an ~80% compression ratio. I assume those files were stored via `pickle.dump()` so there seems to be quite a bit of low-hanging fruit there.

**Comment by willkg** [comment]
@gabrielesvelto I'm a Python person and I've got some free time. What can I do to help you on this?

**Comment by gabrielesvelto** [comment]
@willkg if could change the cache-handling code to store the cache files in compressed format it would improve the cache effective size significantly. I've got no preference about what should be used, gzip seems enough but if you have better alternatives I'm fine with them.

I've had a quick glance at the pickle format and it seems that in the current version it's a binary representation of the object but w/o compression:

https://docs.python.org/3/library/pickle.html#data-stream-format

**Comment by willkg** [comment]
I used @rhelmer's approach and tried gzip and bz2--both are in the python stdlib. I used the highest compression levels for both (it's the default in both cases).

```
> ls -l cache*
cache.orig:
total 13944
-rw-rw-r-- 1 willkg willkg 14136768 Jun 22 11:52 44E4EC8C2F41492B9369D6B9A059577C2@xul.pdb
-rw-rw-r-- 1 willkg willkg   138777 Jun 22 11:52 D74F79EB1F8D4A45ABCD2F476CCABACC2@wntdll.pdb

cache.gzip:
total 2784
-rw-rw-r-- 1 willkg willkg 2801576 Jun 22 14:09 44E4EC8C2F41492B9369D6B9A059577C2@xul.pdb
-rw-rw-r-- 1 willkg willkg   46257 Jun 22 14:09 D74F79EB1F8D4A45ABCD2F476CCABACC2@wntdll.pdb

cache.bz2:
total 2304
-rw-rw-r-- 1 willkg willkg 2312957 Jun 22 14:17 44E4EC8C2F41492B9369D6B9A059577C2@xul.pdb
-rw-rw-r-- 1 willkg willkg   43572 Jun 22 14:17 D74F79EB1F8D4A45ABCD2F476CCABACC2@wntdll.pdb
```

So for the biggest of those two files, we went from 14.1mb to 2.3mb with bz2. That's ~83% savings. That lines up with what @gabrielesvelto saw.

I'll throw together a PR.
