### ISSUE TITLE
switch from bin/ to snappy/ and a python module

### ISSUE THREAD

**Issue by willkg** [mozilla/Snappy-Symbolication-Server#30]
Right now, all the files are being imported directly off of the sys path. This involves adding the `bin/` directory to the sys path before importing things.

Python has a module system that lets you group Python modules into a namespace.

A better way to structure snappy is to move the snappy code files into a `snappy/` directory, add a `__init__.py` file to that directory (it can be empty--that's fine) and then you can import files using lines like:

```
from snappy.quickstart_Config import config
```

**Comment by bytesized** [comment]
Fixed in PR #35
