### ISSUE TITLE
run a lint pass to catch errors

### ISSUE THREAD

**Issue by willkg** [mozilla/Snappy-Symbolication-Server#31]
The code has a few things that are defined in the same namespace a couple of times as well as some missing symbols and unused imports and some other things.

These sorts of things can all be caught by running a lint pass on the code.

I suggest running pyflakes on the code and test directories to catch errors that aren't currently being caught by tests.

https://pypi.python.org/pypi/pyflakes

**Comment by bytesized** [comment]
Code linted. Future linting will now be done automatically via Travis CI.
