### ISSUE TITLE
set up with travis ci or circle ci

### ISSUE THREAD

**Issue by willkg** [mozilla/Snappy-Symbolication-Server#32]
Github can work with Travis CI and Circle CI and other testing systems to run the test suite on PRs after they're created. This makes it a lot easier for people to contribute fixes and it also makes it less likely errors get merged into master and then deployed.

Travis: https://travis-ci.org/

Circle: https://circleci.com/

**Comment by bytesized** [comment]
Support for Travis CI added in PR #42.

**Comment by willkg** [comment]
This isn't actually set up, yet. We have to enable the Travis CI webhook.

**Comment by willkg** [comment]
I set up the webhook and see it kicking off with PR #46.

Closing this out again.
