### ISSUE TITLE
sha256 for psutil is incorrect on Windows

### ISSUE THREAD

**Issue by dblohm7** [mozilla/Snappy-Symbolication-Server#45]
On Windows the sha256 hash for psutil 4.3.1 needs to be b0c5bf0d2a29a6f18ac22e2d24210730dca458c9f961914289c9e027ccb5ae43

**Comment by bytesized** [comment]
This is actually done as part of PR #42. Still waiting for review on it.

**Comment by bytesized** [comment]
Now that PR #42 has merged, this issue should be resolved.
