### ISSUE TITLE
zlib compressed symbols not supported

### ISSUE THREAD

**Issue by hcs64** [mozilla/Snappy-Symbolication-Server#68]
With an empty DiskCache and memcached, run:
`curl -d '{"debug":true, "action": "cacheGet", "libName":"ntdll.pdb", "breakpadId":"F1867DA631674FDFBABCD47A3744E1BF1"}' 127.0.0.1:8888`

response:
`{"path": null}`

DiskCache log:
```2017-01-26 16:57:17,682 ERROR   10598   Exception when requesting symbol file at https://s3-us-west-2.amazonaws.com/org.mozilla.crash-stats.symbols-public/v1/ntdll.pdb/F1867DA631674FDFBABCD47A3744E1BF1/ntdll.sym: Not a gzipped file```

**Comment by bytesized** [comment]
@hcs64 I am closing this now that PR #69 has been merged.
